### ISSUE TITLE
install failure during gifcli install on macOS

### ISSUE THREAD

**Issue by lotruheawea** [etherisc/GIF#165]
Dear devs team,

when running the sandbox tutorial in a seperate conda environment, I get this when executing `npm install -g @etherisc/gifcli`:

```
> gc-stats@1.4.0 install /Users/ottor/local/lib/node_modules/@etherisc/gifcli/node_modules/gc-stats
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://node-binaries.s3.amazonaws.com/gcstats/v1.4.0/Release/node-v83-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for gc-stats@1.4.0 and node@14.15.1 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
  CXX(target) Release/obj.target/gcstats/src/gcstats.o
c++: error: unrecognized command line option ‘-stdlib=libc++’
make: *** [Release/obj.target/gcstats/src/gcstats.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "build" "--fallback-to-build" "--module=/Users/ottor/local/lib/node_modules/@etherisc/gifcli/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v83-darwin-x64/gcstats.node" "--module_name=gcstats" "--module_path=/Users/ottor/local/lib/node_modules/@etherisc/gifcli/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v83-darwin-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /Users/ottor/local/lib/node_modules/@etherisc/gifcli/node_modules/gc-stats
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/bin/node-gyp build --fallback-to-build --module=/Users/ottor/local/lib/node_modules/@etherisc/gifcli/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v83-darwin-x64/gcstats.node --module_name=gcstats --module_path=/Users/ottor/local/lib/node_modules/@etherisc/gifcli/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v83-darwin-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/ottor/local/lib/node_modules/@etherisc/gifcli/node_modules/gc-stats/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Darwin 20.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/ottor/local/lib/node_modules/@etherisc/gifcli/node_modules/gc-stats/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/ottor/local/lib/node_modules/@etherisc/gifcli/node_modules/gc-stats
node-pre-gyp ERR! node -v v14.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/bin/node-gyp build --fallback-to-build --module=/Users/ottor/local/lib/node_modules/@etherisc/gifcli/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v83-darwin-x64/gcstats.node --module_name=gcstats --module_path=/Users/ottor/local/lib/node_modules/@etherisc/gifcli/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v83-darwin-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
```

I do not know if you can give feedback on that failing `gc-stats` dependency. If you have a working node and npm version combination for Darwin 20.6.0, I'd be happy to get that also. I am very new to NodeJS. Thanks!

**Comment by christoph2806** [comment]
Hi, during the last year we did a complete rework of the GIF off-chain environment, so gifcli is no longer supported.
Currently you only need gif-connect, gif-contracts and gif-interface. We are in the process of documenting the new setup, and we will publish additional tutorials etc., and we will offer a maintained sandbox environment for this setup.
So maybe it makes sense to wait until we have finished the new setup.
If you have some urgend demand please let us know.

**Comment by christoph2806** [comment]
The current release 1.1.43-staging release "chalmers" should be pretty stable but we simply need to add some install instructions in the Readme.
